//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FysioRoadmap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FRMModelContainer : DbContext
    {
        public FRMModelContainer()
            : base("name=FRMModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Verzekerde> VerzekerdeSet { get; set; }
        public virtual DbSet<Verzekering> VerzekeringSet { get; set; }
        public virtual DbSet<Afspraak> AfspraakSet { get; set; }
        public virtual DbSet<Verzekeringsregel> VerzekeringsregelSet { get; set; }
        public virtual DbSet<Declaratie> DeclaratieSet { get; set; }
    }
}
