//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FysioRoadmap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verzekering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Verzekering()
        {
            this.VerzekerdeSet = new HashSet<Verzekerde>();
            this.VerzekeringsregelSet = new HashSet<Verzekeringsregel>();
        }
    
        public int Id { get; set; }
        public string Naamverzekering { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verzekerde> VerzekerdeSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Verzekeringsregel> VerzekeringsregelSet { get; set; }
    }
}
